version: '1'

boxes:
  dev:
    image: "ubuntu/trusty64"
    ports:
      - 8080:80:127.0.0.1
    networks:
      private_network:
    provision:
      core:
        - provision/base.sh:privileged
      #utils:
        #- provision/vim.sh
